name: Where DFIR Meets IT
description: ForensicITGuy's blog about DFIR and tech
meta_description: "ForensicITGuy's blog about DFIR and tech"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# markdown: kramdown
# highlighter: rouge
logo: false
paginate: 15
paginate-path: "/page/:num"
baseurl: ""
domain_name: "https://forensicitguy.github.io"
google_analytics: "UA-155060013-1"
plugins: [jekyll-paginate, jekyll-include-cache]

# Details for the RSS feed generator
url: "https://forensicitguy.github.io"
author: "Tony Lambert (ForensicITGuy)"
author-bio: "An educator that happens to do security things for Red Canary"

# Disqus config
disqus-shortname: "ForensicITGuy"
