baseURL = "https://example.com"
languageCode = "en-us"
title = "Some Title"
theme = "bare-hugo-theme"
enableGitInfo = true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["post"]
author = "Joe Bloggs"
email = "hello@hello-world.com"
repoLink = "https://github.com/orf/bare-hugo-theme"
description = 'Something about myself'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true

[[params.social]]
icon = "github"
url = "https://github.com/orf/"
